<?xml version="1.0" encoding="UTF-8" ?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.tachyonmcp</groupId>
    <artifactId>tachyon-examples</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Tachyon MCP Examples</name>
    <url>https://github.com/tachyonmcp/tachyon</url>

    <modules>
        <module>echo-kotlin</module>
        <module>langchain4j-mcp</module>
        <module>mcp-java</module>
        <module>mcp-skills</module>
        <module>temporal</module>
        <module>weather-mcp-kotlin</module>
        <module>weather-mcp-spring-boot</module>
        <module>weather-mcp</module>
    </modules>
    <profiles>
        <profile>
            <id>snapshot-examples</id>
            <activation>
                <property>
                    <name>tachyon.version</name>
                    <value>1.0.0-SNAPSHOT</value>
                </property>
            </activation>
            <modules>
                <module>weather-mcp-spring-boot</module>
            </modules>
        </profile>
    </profiles>
</project>
