spring.application.name=weather-mcp-spring-boot
spring.main.web-application-type=none
spring.main.keep-alive=true
tachyon.name=weather-server
tachyon.version=1.0.0-SNAPSHOT
tachyon.host=127.0.0.1
tachyon.port=8080
